tasks:
  - init: npm install # runs during prebuild
    command: |
      export HMR_HOST=`gp url 5173`
    before: .gitpod/before.sh

ports:
  - port: 5173
    onOpen: ignore

image: gitpod/workspace-full-vnc

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - humao.rest-client
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
