
tasks:
  - init: npm install # runs during prebuild
    command: npm run dev

ports:
  - port: 3000
    onOpen: ignore



vscode:
  extensions:
    - humao.rest-client
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
