
tasks:
  - init: npm install # runs during prebuild
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev

ports:
  - port: 3000
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true



vscode:
  extensions:
    - humao.rest-client
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
