apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddiehub-finder-deployment
  labels:
    app: eddiehub-finder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eddiehub-finder
  template:
    metadata:
      labels:
        app: eddiehub-finder
    spec:
      containers:
        - name: finder
          image: ghcr.io/eddiehubcommunity/finder:latest
          ports:
            - containerPort: 3000
          env:
            - name: FINDER_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: finder-gh-client-id-secret
                  key: FINDER_GITHUB_CLIENT_ID
            - name: FINDER_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finder-gh-client-secret
                  key: FINDER_GITHUB_CLIENT_SECRET
