on:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked 
      - review_requested 
      - review_request_removed 
      - auto_merge_enabled 
      - auto_merge_disabled
  pull_request_review:
  pull_request_review_comment:
  push:
  registry_package:
  release:
  repository_dispatch:
  status:
  watch:

jobs:
  statistics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/statistics@main
        with:
          api-key: ${{ secrets.API_TOKEN }}
          api-url: ${{ secrets.API_URL }}/github/events
